wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1712349045
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 24
      4: 3.9.18
      5: 0.12.16
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 64
content_hooks:
  desc: null
  value:
  - conv0.0
dataset:
  desc: null
  value: None
dataset_params:
  desc: null
  value: null
feature_load_artifact:
  desc: null
  value: bert-tiny-eecq0ads:latest
feature_model:
  desc: null
  value: true
feature_model_params:
  desc: null
  value:
    batch_size: 64
    cloze_len: 8
    cloze_perc: 0.2
    csv_weights:
    - 1
    - 1
    dataset: CSVs
    dropout: 0.2
    embedding: none
    file_names:
    - gp_single.csv
    - energy_norm_single.csv
    last_nonempty: null
    layers: 8
    mask_rand_none_split:
    - 0.8
    - 0.1
    - 0.1
    masking: token-pre
    model: CNN
    out_conv_channels: 4096
    relevant_cols:
    - x_1
    seq_len: 256
    transform: masking
lamb_content:
  desc: null
  value: 1
lamb_dis:
  desc: null
  value: 0
lamb_style:
  desc: null
  value: 10
last_hook:
  desc: null
  value: conv1.0
lr:
  desc: null
  value: 0.001957571978839115
metrics:
  desc: null
  value:
  - stval_PR
  - stval_fin
  - stval_perceptual
  - stval_MAE
model:
  desc: null
  value: Iter
model_params:
  desc: null
  value:
    batch_size: 64
    in_channels: 1
    seq_len: 256
num_iters:
  desc: null
  value: 500
relevant_cols:
  desc: null
  value:
  - x_1
save_path:
  desc: null
  value: ../nets/bert-tiny
seq_len:
  desc: null
  value: 256
skip_train:
  desc: null
  value: true
st_content_params:
  desc: null
  value:
    batch_size: 64
    dataset: CSV
    file_name: gp_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    transform: none
st_dataset:
  desc: null
  value: true
st_iter_params:
  desc: null
  value:
    criterion: perceptual
    criterion_params:
      content_hooks:
      - conv0.0
      lamb_content: 1
      lamb_dis: 0
      lamb_kl: 1
      lamb_style: 10
      last_hook: conv1.0
      style_hooks:
      - conv1.0
      style_loss: mean_std
    lr: 0.001
    lr_decay: 1
    lr_full: 200
    num_iters: 500
    optimizer: Adam
st_loss:
  desc: null
  value: perceptual
st_lr_full:
  desc: null
  value: 200
st_style_params:
  desc: null
  value:
    batch_size: 64
    dataset: CSV
    file_name: energy_norm_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    transform: none
stc_dataset:
  desc: null
  value: CSV
stc_dataset_params:
  desc: null
  value:
    batch_size: 64
    file_path: ../data/gp_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    target_col: null
    test_perc: 0.1
    valid_perc: 0.1
sts_dataset:
  desc: null
  value: CSV
sts_dataset_params:
  desc: null
  value:
    batch_size: 64
    file_path: ../data/energy_norm_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    target_col: null
    test_perc: 0.1
    valid_perc: 0.1
style_hooks:
  desc: null
  value:
  - conv1.0
training_params:
  desc: null
  value:
    criterion: val_perceptual
    criterion_params:
      content_hooks:
      - conv0.0
      lamb_content: 1
      lamb_dis: 0
      lamb_kl: 1
      lamb_style: 10
      last_hook: conv1.0
      style_hooks:
      - conv1.0
      style_loss: mean_std
    epochs: 5
    optim_params:
      lr: 0.001957571978839115
      lr_decay: 1
      lr_delay: 0
      lr_full: 0
      lr_warmup: 0
    optimizer: Adam
    shuffle_style: null
transform:
  desc: null
  value: none
wandb:
  desc: null
  value: true
