wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1712346559
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 24
      4: 3.9.18
      5: 0.12.16
      8:
      - 4
      - 5
    visualize:
      reconstruct_train0:
        panel_config:
          fieldSettings:
            lineKey: lineKey
            lineVal: lineVal
            step: step
          panelDefId: wandb/lineseries/v0
          stringSettings:
            title: Reconstruction (train)
            xname: x
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: reconstruct_train0_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      reconstruct_val0:
        panel_config:
          fieldSettings:
            lineKey: lineKey
            lineVal: lineVal
            step: step
          panelDefId: wandb/lineseries/v0
          stringSettings:
            title: Reconstruction (val)
            xname: x
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: reconstruct_val0_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 64
content_hooks:
  desc: null
  value:
  - conv0.0
dataset:
  desc: null
  value: None
dataset_params:
  desc: null
  value:
    batch_size: 64
    csv_weights:
    - 1
    - 1
    file_paths:
    - ../data/gp_single.csv
    - ../data/energy_norm_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    target_col: null
    test_perc: 0.1
    transform: masking
    transform_params:
      cloze_len: 8
      cloze_perc: 0.2
      mask_rand_none_split:
      - 0.8
      - 0.1
      - 0.1
    valid_perc: 0.1
feature_load_artifact:
  desc: null
  value: bert-tiny-eecq0ads:latest
feature_model:
  desc: null
  value: true
feature_model_params:
  desc: null
  value:
    batch_size: 64
    cloze_len: 8
    cloze_perc: 0.2
    csv_weights:
    - 1
    - 1
    dataset: CSVs
    dropout: 0.2
    embedding: none
    file_names:
    - gp_single.csv
    - energy_norm_single.csv
    last_nonempty: null
    layers: 8
    mask_rand_none_split:
    - 0.8
    - 0.1
    - 0.1
    masking: token-pre
    model: CNN
    out_conv_channels: 4096
    relevant_cols:
    - x_1
    seq_len: 256
    transform: masking
lamb_content:
  desc: null
  value: 1
lamb_dis:
  desc: null
  value: 0
lamb_style:
  desc: null
  value: 10
last_hook:
  desc: null
  value: conv1.0
metrics:
  desc: null
  value:
  - stval_PR
  - stval_fin
  - stval_perceptual
  - stval_MAE
model:
  desc: null
  value: Iter
model_params:
  desc: null
  value:
    context_dim: 16
    context_layers: 1
    context_size: 16
    d_latent: 8
    d_latent_style: 4
    d_model: 128
    dim_feedforward: 512
    dropout: 0.1
    embedding: conv
    final_layer: true
    in_channels: 1
    is_vae: true
    keep_latent: true
    layers: 2
    masking: token-post
    mode: factorised
    n_heads: 8
    out_channels: 1
    pe_after_latent: true
    vae_dist: gaussian
    vae_embedding: none
num_iters:
  desc: null
  value: 5
relevant_cols:
  desc: null
  value:
  - x_1
save_path:
  desc: null
  value: ../nets/bert-tiny
seq_len:
  desc: null
  value: 256
skip_train:
  desc: null
  value: true
st_content_params:
  desc: null
  value:
    batch_size: 64
    dataset: CSV
    file_name: gp_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    transform: none
st_dataset:
  desc: null
  value: true
st_iter_params:
  desc: null
  value:
    criterion: perceptual
    criterion_params:
      content_hooks:
      - conv0.0
      lamb_content: 1
      lamb_dis: 0
      lamb_kl: 0.0004
      lamb_style: 10
      last_hook: conv1.0
      style_hooks:
      - conv1.0
      style_loss: mean_std
    lr: 0.001
    lr_decay: 1
    lr_full: 20
    num_iters: 0
    optimizer: Adam
st_loss:
  desc: null
  value: perceptual
st_lr:
  desc: null
  value: 0.041077523155831026
st_lr_decay:
  desc: null
  value: 0.7454756725877172
st_lr_full:
  desc: null
  value: 200
st_style_params:
  desc: null
  value:
    batch_size: 64
    dataset: CSV
    file_name: energy_norm_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    transform: none
stc_dataset:
  desc: null
  value: CSV
stc_dataset_params:
  desc: null
  value:
    batch_size: 64
    file_path: ../data/gp_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    target_col: null
    test_perc: 0.1
    valid_perc: 0.1
sts_dataset:
  desc: null
  value: CSV
sts_dataset_params:
  desc: null
  value:
    batch_size: 64
    file_path: ../data/energy_norm_single.csv
    relevant_cols:
    - x_1
    seq_len: 256
    target_col: null
    test_perc: 0.1
    valid_perc: 0.1
style_hooks:
  desc: null
  value:
  - conv1.0
training_params:
  desc: null
  value:
    criterion: DIS-perceptual
    criterion_params:
      content_hooks:
      - conv0.0
      lamb_content: 1
      lamb_dis: 0
      lamb_kl: 0.0004
      lamb_style: 10
      last_hook: conv1.0
      style_hooks:
      - conv1.0
      style_loss: mean_std
    epochs: 1
    optim_params:
      lr: 0.001
      lr_decay: 1
      lr_delay: 0
      lr_full: 4
      lr_warmup: 0
    optimizer: Adam
    shuffle_style: half
transform:
  desc: null
  value: none
wandb:
  desc: null
  value: true
